kcw_django/urls.py
from django.contrib import admin
from django.urls import path
from kuser.views import index, RegisterView, LoginView, Logout
from product.views import ProductList, ProductCreate, ProductDetail, ProductListAPI, ProductDetailAPI
from order.views import OrderCreate, OrderList
from board.views import BoardList, BoardWrite, BoardDetail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    # class의 경우 as_view()의 method를 사용해야함
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view()),
    path('logout/', Logout),
    path('product/', ProductList.as_view()),
    path('product/create/', ProductCreate.as_view()),
    path('product/<int:pk>/', ProductDetail.as_view()),
    path('order/', OrderList.as_view()),
    path('order/create/', OrderCreate.as_view()),
    path('board/', BoardList.as_view()),
    path('board/write/', BoardWrite.as_view()),
    path('board/<int:pk>/', BoardDetail.as_view()),
    path('api/product', ProductListAPI.as_view()),
    path('api/product/<int:pk>/', ProductDetailAPI.as_view()),
]

board/models.py
from django.db import models

# Create your models here.


class Board(models.Model):
    title = models.CharField(max_length=128,
                             verbose_name='제목')
    contents = models.TextField(verbose_name='게시글')
    writer = models.ForeignKey('kuser.Kuser', on_delete=models.CASCADE,
                               verbose_name='작성자')
    register_date = models.DateTimeField(auto_now_add=True,
                                         verbose_name='등록날짜')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'kcw_board'
        verbose_name = '게시판'
        verbose_name_plural = '게시판'

board/forms.py
from django import forms
from .models import Board


class WriteForm(forms.Form):
    title = forms.CharField(
        error_messages={
            'required': '제목을 입력해주세요.'
        },
        max_length=128, label='제목'
    )
    contents = forms.CharField(
        error_messages={
            'required': '게시글을 입력해주세요.'
        },
        label='게시글명'
    )

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        contents = cleaned_data.get('contents')

        if not(title and contents):
            if title is None:
                self.add_error('title', '값이 없습니다.')
            if contents is None:
                self.add_error('contents', '값이 없습니다.')

board/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView
from django.utils.decorators import method_decorator
from kuser.decorators import login_required
from .models import Board
from .forms import WriteForm
from kuser.models import Kuser

# Create your views here.


class BoardList(ListView):
    model = Board
    template_name = 'board.html'
    context_object_name = 'board_list'
    paginate_by = 10


@method_decorator(login_required, name='dispatch')
class BoardWrite(FormView):
    template_name = 'board_write.html'
    form_class = WriteForm
    success_url = '/board/'

    def form_valid(self, form):
        user = self.request.session['user']
        board = Board(
            title=form.data.get('title'),
            contents=form.data.get('contents'),
            writer=Kuser.objects.get(email=user)
        )
        board.save()

        return super().form_valid(form)


class BoardDetail(DetailView):
    template_name = 'board_detail.html'
    queryset = Board.objects.all()
    context_object_name = 'board'

order/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.edit import FormView
from django.utils.decorators import method_decorator
from django.db import transaction
from kuser.decorators import login_required
from kuser.models import Kuser
from product.models import Product
from .forms import RegisterForm
from .models import Order

# Create your views here.


@method_decorator(login_required, name='dispatch')
class OrderCreate(FormView):
    form_class = RegisterForm
    success_url = '/product/'

    def form_valid(self, form):
        with transaction.atomic():
            prod = Product.objects.get(pk=form.data.get('product'))
            order = Order(
                quantity=form.data.get('quantity'),
                product=prod,
                kuser=Kuser.objects.get(
                    email=self.request.session.get('user')),
            )
            order.save()
            prod.stock -= int(form.data.get('quantity'))
            prod.save()

        return super().form_valid(form)

    def form_invalid(self, form):
        return redirect('/product/' + str(form.data.get('product')))

    def get_form_kwargs(self, **kwargs):
        kw = super().get_form_kwargs(**kwargs)
        kw.update({
            'request': self.request
        })
        return kw


@method_decorator(login_required, name='dispatch')
class OrderList(ListView):
    template_name = 'order.html'
    context_object_name = 'order_list'

    # 오버라이딩
    def get_queryset(self, **kwargs):
        queryset = Order.objects.filter(
            kuser__email=self.request.session.get('user'))
        return queryset

board/templates/board.html
{% extends "base.html" %}
{% load humanize %}
<!-- {% block header %}
<script>
  function board_detail(id){
    $.ajax({
      url: "/api/board/" + id,
      success: function( result ) {
        $("#board-" + id).popover({
          html: true,
          content: result.name + "<br/>" + result.price
        }).popover('show');
      }
    });
  }
  function board_leave(id){
    $("#board-" + id).popover('hide');
  }
  $(document).ready(function(){});
</script>
{% endblock %} -->
{% block contents %}
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Woong's Market</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/board/">Board</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/product/">Prodct</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/order/">Order</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<br>
<div class="row mt-5">
  <div class="col-12">
    <table class="table table-light">
      <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">제목</th>
          <th scope="col">작성자</th>
          <th scope="col">등록날짜</th>
        </tr>
      </thead>
      <tbody class="text-dark">
        {% for board in board_list %}
        <tr>
          <th scope="row">{{ board.id }}</th>
          <th scope="row"><a href="/board/{{ board.id }}">{{ board.title }}</a></th>
          <th scope="row">{{ board.writer.nickname }}</th>
          <th scope="row">{{ board.register_date|date:'Y-m-d H:i' }}</th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% if is_paginated %}
<div>
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">&laquo;</a>
    </li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <a class="page-link">{{ i }} <span class="sr-only">(current)</span></a>
        </li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">&raquo;</a>
    </li>
    {% endif %}
  </ul>
</div>
{% endif %}
<div class="row">
  <div class="col-12">
    <button type="button" class="btn btn-primary" onclick="location.href='/board/write/'">글쓰기</button>
    <!-- <a href="/product/">목록보기</a> -->
  </div>
</div>
{% endblock %}

board/templates/board_detail.html
{% extends "base.html" %}
{% load humanize %}
{% block contents %}
<div class="row mt-5">
  <div class="col-12">
    <div class="card" style="width: 100%">
      <div class="card-body">
        <h5 class="card-title">{{ board.title }}</h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">작성자 : {{ board.writer.email }}</li>
        <li class="list-group-item">등록날짜 : {{ board.register_date|date:'Y-m-d H:i' }}</li>
        <li class="list-group-item">{{ board.contents|safe }}</li>
      </ul>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <br>
    <button type="button" class="btn btn-primary" onclick="location.href='/board/'">목록보기</button>
    <!-- <a href="/board/">목록보기</a> -->
  </div>
</div>
{% endblock %}

board/templates/board_write.html
{% extends "base.html" %} 
{% block header %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-bs4.min.js"></script>
<script>
   $(document).ready(function() {
        $('#id_contents').summernote({
    placeholder: 'Please fill out the contents.',
    tabsize: 2,
    height: 300,
    focus: true,
    lang: "ko-KR"
    });
  });
</script> 
{% endblock %}
{% block contents %} 
<div class="row mt-5">
    <div class="col-12 text-center">
      <h1>게시글 작성</h1>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-12">
      {{ error }}
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-12">
      <form method="POST" action=".">
        <!-- 크로스 도메인 방지용 -->
        {% csrf_token %} 
        {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {% ifequal field.name 'contents' %}
          <textarea class="form-control" name="{{ field.name }}" id="{{ field.id_for_label }}"></textarea>
          {% else %}
          <input
            type="{{ field.field.widget.input_type }}"
            class="form-control"
            id="{{ field.id_for_label }}"
            placeholder="{{ field.label }}"
            name="{{ field.name }}"
          />
          {% endifequal %}
        </div>
        {% if field.errors %}
        <span style="color: red">{{ field.errors }}</span>
        {% endif %} 
        {% endfor %}
        <button type="submit" class="btn btn-primary">작성완료</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}