kcw_django/urls.py
from django.contrib import admin
from django.urls import path
from kuser.views import index, RegisterView, LoginView, Logout
from product.views import ProductList, ProductCreate, ProductDetail, ProductListAPI, ProductDetailAPI
from order.views import OrderCreate, OrderList
from board.views import BoardList, BoardWrite, BoardDetail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    # class의 경우 as_view()의 method를 사용해야함
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view()),
    path('logout/', Logout),
    path('product/', ProductList.as_view()),
    path('product/create/', ProductCreate.as_view()),
    path('product/<int:pk>/', ProductDetail.as_view()),
    path('order/', OrderList.as_view()),
    path('order/create/', OrderCreate.as_view()),
    path('board/', BoardList.as_view()),
    path('board/write/', BoardWrite.as_view()),
    path('board/<int:pk>/', BoardDetail.as_view()),
    path('api/product', ProductListAPI.as_view()),
    path('api/product/<int:pk>/', ProductDetailAPI.as_view()),
]

product/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=256, verbose_name='상품명')
    price = models.IntegerField(verbose_name='상품가격')
    description = models.TextField(verbose_name='상품설명')
    stock = models.IntegerField(verbose_name='재고')
    register_date = models.DateTimeField(
        auto_now_add=True, verbose_name='등록날짜')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'kcw_product'
        verbose_name = '상품'
        verbose_name_plural = '상품'

product/forms.py
from django import forms
from .models import Product


class RegisterForm(forms.Form):
    name = forms.CharField(
        error_messages={
            'required': '상품명을 입력해주세요.'
        },
        max_length=256, label='상품명'
    )
    price = forms.IntegerField(
        error_messages={
            'required': '상품가격을 입력해주세요.'
        },
        label='상품가격'
    )
    description = forms.CharField(
        error_messages={
            'required': '상품설명을 입력해주세요.'
        },
        label='상품설명'
    )
    stock = forms.IntegerField(
        error_messages={
            'required': '재고을 입력해주세요.'
        },
        label='재고'
    )

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        price = cleaned_data.get('price')
        description = cleaned_data.get('description')
        stock = cleaned_data.get('stock')

        if not(name and price and description and stock):
            if name is None:
                self.add_error('name', '값이 없습니다.')
            if price is None:
                self.add_error('price', '값이 없습니다.')
            if description is None:
                self.add_error('description', '값이 없습니다.')
            if stock is None:
                self.add_error('stock', '값이 없습니다.')

board/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView
from django.utils.decorators import method_decorator
from kuser.decorators import login_required
from .models import Board
from .forms import WriteForm
from kuser.models import Kuser

# Create your views here.


class BoardList(ListView):
    model = Board
    template_name = 'board.html'
    context_object_name = 'board_list'
    paginate_by = 10


@method_decorator(login_required, name='dispatch')
class BoardWrite(FormView):
    template_name = 'board_write.html'
    form_class = WriteForm
    success_url = '/board/'

    def form_valid(self, form):
        user = self.request.session['user']
        board = Board(
            title=form.data.get('title'),
            contents=form.data.get('contents'),
            writer=Kuser.objects.get(email=user)
        )
        board.save()

        return super().form_valid(form)


class BoardDetail(DetailView):
    template_name = 'board_detail.html'
    queryset = Board.objects.all()
    context_object_name = 'board'

product/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView
from django.utils.decorators import method_decorator
from rest_framework import generics
from rest_framework import mixins

from kuser.decorators import admin_required
from .models import Product
from .forms import RegisterForm
from .serializers import ProductSerializer
from order.forms import RegisterForm as OrderForm

# Create your views here.


class ProductListAPI(generics.GenericAPIView, mixins.ListModelMixin):
    serializer_class = ProductSerializer

    def get_queryset(self):
        return Product.objects.all().order_by('id')

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)


class ProductDetailAPI(generics.GenericAPIView, mixins.RetrieveModelMixin):
    serializer_class = ProductSerializer

    def get_queryset(self):
        return Product.objects.all().order_by('id')

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)


class ProductList(ListView):
    model = Product
    template_name = 'product.html'
    context_object_name = 'product_list'


@method_decorator(admin_required, name='dispatch')
class ProductCreate(FormView):
    template_name = 'register_product.html'
    form_class = RegisterForm
    success_url = '/product/'

    def form_valid(self, form):
        product = Product(
            name=form.data.get('name'),
            price=form.data.get('price'),
            description=form.data.get('description'),
            stock=form.data.get('stock')
        )
        product.save()

        return super().form_valid(form)


class ProductDetail(DetailView):
    template_name = 'product_detail.html'
    queryset = Product.objects.all()
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderForm(self.request)
        return context

product/templates/product.html
{% extends "base.html" %}
{% load humanize %}
{% block header %}
<script>
  function product_detail(id){
    $.ajax({
      url: "/api/product/" + id,
      success: function( result ) {
        $("#product-" + id).popover({
          html: true,
          content: "상품 : " + result.name + "<br/>" + "가격 : " + result.price + " 원"
        }).popover('show');
      }
    });
  }
  function product_leave(id){
    $("#product-" + id).popover('hide');
  }
  $(document).ready(function(){});
</script>
{% endblock %}
{% block contents %}
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Woong's Market</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/board/">Board</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/product/">Prodct</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/order/">Order</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<br>
<div class="row mt-5">
  <div class="col-12">
    <table class="table table-light">
      <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">상품명</th>
          <th scope="col">가격</th>
          <th scope="col">등록날짜</th>
        </tr>
      </thead>
      <tbody class="text-dark">
        {% for product in product_list %}
        <tr>
          <th scope="row">{{ product.id }}</th>
          <th scope="row"><a id="product-{{ product.id }}" onmouseenter="product_detail({{ product.id }});" onmouseleave="product_leave({{ product.id }});" href="/product/{{ product.id }}">{{ product.name }}</a></th>
          <th scope="row">{{ product.price|intcomma }} 원</th>
          <th scope="row">{{ product.register_date|date:'Y-m-d H:i' }}</th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

product/templates/product_detail.html
{% extends "base.html" %}
{% load humanize %}
{% block contents %}
<div class="row mt-5">
  <div class="col-12">
    <div class="card" style="width: 100%">
      <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <form method="POST" action="/order/create/">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
              {% ifnotequal field.name 'product' %}
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {% endifnotequal %}
              <input
                type="{{ field.field.widget.input_type }}"
                class="form-control"
                id="{{ field.id_for_label }}"
                placeholder="{{ field.label }}"
                name="{{ field.name }}"
                value="{% ifequal field.name 'product' %}{{product.id}}{% endifequal %}"
              />
            </div>
            {% if field.errors %}
            <span style="color: red">{{ field.errors }}</span>
            {% endif %} 
            {% endfor %}
            <button type="submit" class="btn btn-primary">주문하기</button>
          </form>
        </li>
        <li class="list-group-item">가격 : {{ product.price|intcomma }} 원</li>
        <li class="list-group-item">등록날짜 : {{ product.register_date|date:'Y-m-d H:i' }}</li>
        <li class="list-group-item">재고 : {{ product.stock|intcomma }}</li>
        <li class="list-group-item">{{ product.description|safe }}</li>
      </ul>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <br>
    <button type="button" class="btn btn-primary" onclick="location.href='/product/'">목록보기</button>
    <!-- <a href="/product/">목록보기</a> -->
  </div>
</div>
{% endblock %}

product/templates/register_product.html
{% extends "base.html" %} 
{% block header %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-bs4.min.js"></script>
<script>
   $(document).ready(function() {
        $('#id_description').summernote({
    placeholder: 'Hello Bootstrap 4',
    tabsize: 2,
    height: 300,
    focus: true,
    lang: "ko-KR"
    });
  });
</script> 
{% endblock %}
{% block contents %} 
<div class="row mt-5">
    <div class="col-12 text-center">
      <h1>상품등록</h1>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-12">
      {{ error }}
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-12">
      <form method="POST" action=".">
        <!-- 크로스 도메인 방지용 -->
        {% csrf_token %} 
        {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {% ifequal field.name 'description' %}
          <textarea class="form-control" name="{{ field.name }}" id="{{ field.id_for_label }}"></textarea>
          {% else %}
          <input
            type="{{ field.field.widget.input_type }}"
            class="form-control"
            id="{{ field.id_for_label }}"
            placeholder="{{ field.label }}"
            name="{{ field.name }}"
          />
          {% endifequal %}
        </div>
        {% if field.errors %}
        <span style="color: red">{{ field.errors }}</span>
        {% endif %} 
        {% endfor %}
        <button type="submit" class="btn btn-primary">등록</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}